OPENAI_API_KEY: "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"
LINE_CHANNEL_ACCESS_TOKEN: "ff4041b82fee02aa1eb6b88d53cce8f3"
LINE_CHANNEL_SECRET: "NxYmg138/UsnRYr/M/wL6jW30qChzR4hXYnFD/p0R47MAtFQ/+RD9ypaHdbG1S0QFqSDl161tKTTkMzB09dB6IrxAv38dMEm2HdZJDYEwt7tUG9Ib6kkoHT3iYBXxG6uO9ybHFIJykTEfZK7MV1JFAdB04t89/1O/w1cDnyilFU="
